# Generated by Django 3.2.5 on 2021-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
